### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by Bensebabillal** [ricnaaru/adv_image_picker#1]
macbook adv_image_picker-master $  flutter doctor -v
[✓] Flutter (Channel master, v1.15.3-pre.37, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.15.3-pre.37 at /Users/macbook/flutter
    • Framework revision 6dc3bfaa98 (31 hours ago), 2020-02-07 18:28:02 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86    • Android 10 (API 29) (emulator)
    • iPhone de PC GAMER        • dd3c66ae2a15829591f6364970aade158b31a2df • ios            • iOS 13.3
    • Chrome                    • chrome                                   • web-javascript • Google Chrome 76.0.3809.132
    • Web Server                • web-server                               • web-javascript • Flutter Tools

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/macbook/flutter/.pub-cache/hosted/pub.dartlang.org/adv_camera-1.0.0+1/android/src/main/java/com/ric/adv_camera/AdvCamera.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/macbook/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Compiler message:
../lib/adv_image_picker.dart:46:21: Error: Getter not found: 'loading'.
    BasicComponents.loading.assetName = loadingAssetName;
                    ^^^^^^^
../lib/adv_image_picker.dart:109:21: Error: Getter not found: 'loading'.
    BasicComponents.loading.assetName = loadingAssetName;
                    ^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/macbook/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 817

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/macbook/flutter/bin/flutter'' finished with non-zero exit value 1

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/macbook/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by ricnaaru** [comment]
sorry for the error, try to use adv_image_picker 1.0.7

please reopen if you find any further related errors
