### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by Bensebabillal** [ricnaaru/adv_image_picker#2]
there is still compilation error : 

════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building AdvLoadingWithBarrier(dirty):
The getter 'theme' was called on null.
Receiver: null
Tried calling: theme

The relevant error-causing widget was
    MaterialApp 
lib/main.dart:12
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      ComponentTheme.of 
package:basic_components/components/component_theme.dart:27
#2      AdvLoadingWithBarrier.build 
package:basic_components/components/adv_loading_with_barrier.dart:27
#3      StatelessElement.build 
package:flutter/…/widgets/framework.dart:4561
#4      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4492
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The getter 'theme' was called on null.
Receiver: null
Tried calling: theme
The relevant error-causing widget was
    MaterialApp 
lib/main.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The getter 'theme' was called on null.
Receiver: null
Tried calling: theme
The relevant error-causing widget was
    MaterialApp 
lib/main.dart:12
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 199324 pixels on the right.
The relevant error-causing widget was
    MaterialApp 
lib/main.dart:12
════════════════════════════════════════════════════════════════════════════════

thanks .

**Comment by ricnaaru** [comment]
sorry, please try again with version 1.0.7

**Comment by Bensebabillal** [comment]
there is still this error : [https://ibb.co/JRZBkcK](url)

**Comment by Bensebabillal** [comment]
[<a href="https://ibb.co/JRZBkcK"><img src="https://i.ibb.co/hR078gy/Screenshot-2020-02-19-at-19-05-00.png" alt="Screenshot-2020-02-19-at-19-05-00" border="0"></a>](url)

**Comment by ricnaaru** [comment]
sorry, but i check on my device it compiles fine, what version were you using?

**Comment by ricnaaru** [comment]
please try the latest version (1.2.0) and if the problem still persists, please kindly reopen this thread. Thanks!
